Update github-actions-demo.yml

diff --git a/.github/workflows/github-actions-demo.yml b/.github/workflows/github-actions-demo.yml
--- a/.github/workflows/github-actions-demo.yml
+++ b/.github/workflows/github-actions-demo.yml
@@ -27,6 +27,12 @@ jobs:
         run: |
           echo "Username: ${{ secrets.USERNAME }}"
           echo "Password: ${{ secrets.PASSWORD }}"
+          if [[ "${{ secrets.USERNAME }}" == 'dev' && "${{ secrets.PASSWORD }}" == 'password' ]]; then
+          echo "Both USERNAME and PASSWORD are valid. Running this step."
+          else
+          echo "Either USERNAME or PASSWORD is invalid. Skipping this step."
+          exit 1  # Exit the step with an error code to indicate it was skipped
+          fi
       - run: echo "💡 The ${{ github.repository }} repository has been cloned to the runner."
       - name: List files in the repository
         run: |
